version: 0.2

# This buildspec runs when buildspec-override:true is set in the workflow

phases:
  install:
    commands:
      - echo "Install phase - setting up environment"
      
  pre_build:
    commands:
      - echo "Pre-build phase - before GitHub Actions runner starts"
      - echo "Current directory is $(pwd)"
      
  post_build:
    commands:
      - echo "Post-build phase - after GitHub Actions job completes"
