apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  labels:
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/version: 24.1.2
    helm.sh/chart: clickhouse-24.1.18
  name: signoz-clickhouse
  namespace: signoz
spec:
  configuration:
    clusters:
    - layout:
        replicasCount: 1
        shardsCount: 1
      name: cluster
      templates:
        podTemplate: pod-template
    files:
      config.d/crash.xml: |
        <clickhouse>
          <send_crash_reports replace="replace">
            <enabled>false</enabled>
          </send_crash_reports>
        </clickhouse>
      config.d/formatting.xml: |
        <clickhouse>
          <logger>
            <formatting replace="replace">
              <type>json</type>
              <names>
                <date_time>date_time</date_time>
                <thread_name>thread_name</thread_name>
                <thread_id>thread_id</thread_id>
                <level>level</level>
                <query_id>query_id</query_id>
                <logger_name>logger_name</logger_name>
                <message>message</message>
                <source_file>source_file</source_file>
                <source_line>source_line</source_line>
              </names>
            </formatting>
          </logger>
        </clickhouse>
      config.d/load.xml: |
        <clickhouse>
          <async_load_databases replace="replace">false</async_load_databases>
        </clickhouse>
      config.d/storage.xml: |
        <clickhouse>
          <storage_configuration>
            <disks>
              <!--
                default disk is special, it always exists even if not explicitly configured here,
                but you can't change it's path here (you should use <path> on top level config instead)
              -->
              <default>
                <!--
                  You can reserve some amount of free space on any disk (including default) by adding
                  keep_free_space_bytes tag.
                -->
                <keep_free_space_bytes>10485760</keep_free_space_bytes>
              </default>
              <s3>
                <type>s3</type>
                <endpoint>https://signoz-cold-storage-734910191031.s3.ap-south-1.amazonaws.com/data/</endpoint>
                <use_environment_credentials>true</use_environment_credentials>
              </s3>
            </disks>
            <policies>
              <tiered>
                <volumes>
                  <default>
                    <disk>default</disk>
                  </default>
                  <s3>
                    <disk>s3</disk>
                    <perform_ttl_move_on_insert>0</perform_ttl_move_on_insert>
                    <prefer_not_to_merge>1</prefer_not_to_merge>
                  </s3>
                </volumes>
                <move_factor>0</move_factor>
              </tiered>
            </policies>
          </storage_configuration>
        </clickhouse>
      config.d/system_log.xml: |
        <clickhouse>
          <text_log>
            <ttl>event_date + INTERVAL 3 DAY DELETE</ttl>
          </text_log>
          <latency_log>
            <ttl>event_date + INTERVAL 3 DAY DELETE</ttl>
          </latency_log>
          <error_log>
            <ttl>event_date + INTERVAL 7 DAY DELETE</ttl>
          </error_log>
          <query_metric_log>
            <ttl>event_date + INTERVAL 3 DAY DELETE</ttl>
          </query_metric_log>
        </clickhouse>
      events.proto: |
        syntax = "proto3";
        message Event {
          string uuid = 1;
          string event = 2;
          string properties = 3;
          string timestamp = 4;
          uint64 team_id = 5;
          string distinct_id = 6;
          string created_at = 7;
          string elements_chain = 8;
        }
    profiles:
      admin/query_plan_max_limit_for_lazy_materialization: "0"
      admin/secondary_indices_enable_bulk_filtering: "0"
      default/allow_experimental_window_functions: "1"
      default/allow_nondeterministic_mutations: "1"
      default/query_plan_max_limit_for_lazy_materialization: "0"
      default/secondary_indices_enable_bulk_filtering: "0"
    settings:
      format_schema_path: /etc/clickhouse-server/config.d/
      prometheus/endpoint: /metrics
      prometheus/port: 9363
      user_defined_executable_functions_config: /etc/clickhouse-server/functions/custom-functions.xml
      user_scripts_path: /var/lib/clickhouse/user_scripts/
    users:
      admin/networks/ip:
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 198.18.0.0/15
      - 192.168.0.0/16
      admin/password: 27ff0399-0d3a-4bd8-919d-17c2181e6fb9
      admin/profile: default
      admin/quota: default
    zookeeper:
      nodes:
      - host: signoz-zookeeper-0.signoz-zookeeper-headless
        port: 2181
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volumeclaim-template
      serviceTemplate: service-template
  templates:
    podTemplates:
    - metadata:
        annotations:
          signoz.io/path: /metrics
          signoz.io/port: "9363"
          signoz.io/scrape: "true"
        labels:
          app.kubernetes.io/component: clickhouse
          app.kubernetes.io/instance: signoz
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: clickhouse
          app.kubernetes.io/version: 24.1.2
          helm.sh/chart: clickhouse-24.1.18
      name: pod-template
      spec:
        containers:
        - command:
          - /bin/bash
          - -c
          - /usr/bin/clickhouse-server --config-file=/etc/clickhouse-server/config.xml
          image: docker.io/clickhouse/clickhouse-server:25.5.6
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 60
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          name: clickhouse
          ports:
          - containerPort: 8123
            name: http
          - containerPort: 9000
            name: client
          - containerPort: 9009
            name: interserver
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 2000m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 2Gi
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
          - mountPath: /var/lib/clickhouse/user_scripts
            name: shared-binary-volume
          - mountPath: /etc/clickhouse-server/functions
            name: custom-functions-volume
          - mountPath: /scripts
            name: scripts
          - mountPath: /var/lib/clickhouse
            name: data-volumeclaim-template
        initContainers:
        - command:
          - sh
          - -c
          - |
            set -e
            version="v0.0.1"
            node_os=$(uname -s | tr '[:upper:]' '[:lower:]')
            node_arch=$(uname -m | sed s/aarch64/arm64/ | sed s/x86_64/amd64/)
            echo "Fetching histogram-binary for ${node_os}/${node_arch}"
            cd /tmp
            wget -O histogram-quantile.tar.gz "https://github.com/SigNoz/signoz/releases/download/histogram-quantile%2F${version}/histogram-quantile_${node_os}_${node_arch}.tar.gz"
            tar -xzf histogram-quantile.tar.gz
            chmod +x histogram-quantile
            mv histogram-quantile /var/lib/clickhouse/user_scripts/histogramQuantile
            echo "histogram-quantile installed successfully"
          image: docker.io/alpine:3.18.2
          imagePullPolicy: IfNotPresent
          name: signoz-clickhouse-udf-init
          volumeMounts:
          - mountPath: /var/lib/clickhouse/user_scripts
            name: shared-binary-volume
        priorityClassName: ""
        securityContext:
          fsGroup: 101
          fsGroupChangePolicy: OnRootMismatch
          runAsGroup: 101
          runAsUser: 101
        serviceAccountName: signoz-clickhouse
        volumes:
        - emptyDir: {}
          name: shared-binary-volume
        - configMap:
            name: signoz-clickhouse-custom-functions
          name: custom-functions-volume
        - configMap:
            name: signoz-clickhouse-scripts
          name: scripts
    serviceTemplates:
    - generateName: signoz-clickhouse
      metadata:
        labels:
          app.kubernetes.io/component: clickhouse
          app.kubernetes.io/instance: signoz
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: clickhouse
          app.kubernetes.io/version: 24.1.2
          helm.sh/chart: clickhouse-24.1.18
      name: service-template
      spec:
        ports:
        - name: http
          port: 8123
        - name: tcp
          port: 9000
        type: ClusterIP
    volumeClaimTemplates:
    - name: data-volumeclaim-template
      reclaimPolicy: Retain
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: gp3
